config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Internal
  resource :session, only: [:new, :create, :destroy]

  # App
  scope :charts do
    get :consumer_indicies, to: "charts#consumer_indicies", as: :consumer_index_chart
  end
  resource :calculator, only: [:show, :create]
  resources :consumer_indicies, only: [:show]

  resources :collections, only: [:index, :new, :update]
  resources :real_estates do
    resources :living_units, path: :units, except: [:index, :new]
  end

  resources :living_units, path: :units, only: [] do
    resources :rentals
    resources :rents, except: [:show, :edit, :update]
    resources :tenants, except: [:show, :edit, :update]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "real_estates#index"
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  include Broadcast::Collection

  delegated_type :collectable, types: ["RealEstate"]
  delegate :name, :childrens, to: :collectable
  store :user_settings, accessors: [:collapse], coder: JSON

  has_many :memberships,
    foreign_key: [:memberable_type, :memberable_id],
    primary_key: [:collectable_type, :collectable_id],
    inverse_of: "user",
    dependent: nil

  class << self
    def accessable(user: Current.user)
      joins(:memberships)
        .where(memberships: { user: })
        .includes(collectable: [:living_units])
    end
  end

  def collapsed_for?(user_id: Current.user.id)
    collapse&.include?(user_id)
  end

  def collapse
    super || []
  end

  def toggle_collapse!(user: Current.user)
    return if user.nil?

    self.collapse = if collapse.include?(user.id)
      collapse.reject! { |user_id| user_id == user.id }
    else
      collapse << user.id
    end
    save!
  end
end

app/models/concerns/broadcast/collection.rb
# frozen_string_literal: true

module Broadcast
  module Collection
    extend ActiveSupport::Concern

    included do
      after_create_commit do
        broadcast_append_later_to(:events, target: :sidebar_list)
      end
      after_update_commit do
        broadcast_update_later_to(:events, target: "name_collection_#{id}", html: name)
        broadcast_replace_later_to(
          Current.user,
          :sidebar,
          target: "sidebar_collection_#{id}",
          locals: {
            user: Current.user,
          },
        )
      end
      after_destroy_commit do
        broadcast_remove_to(:events, target: "sidebar_collection_#{id}")
      end
    end
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  def index
    @collections = Collection.accessable
    render(layout: false)
  end

  def new
  end

  def update
    @collection = Collection.accessable.find(params[:id])

    respond_to do |format|
      if @collection.toggle_collapse!
        format.turbo_stream
        format.html { redirect_to(root_path, notice: "Collection was successfull updated.") }
      end
    end
  end
end

app/helpers/collection_helper.rb
# frozen_string_literal: true

module CollectionHelper
  def collapsed?(collection, user_id:)
    if collection.collapsed_for?(user_id:)
      "open"
    end
  end

  def drawer_link(url, &block)
    link_to(
      url,
      css: "group",
      data: {
        turbo_action: "advance",
        turbo_frame: "main_content",
        drawer_target: "link",
      },
    ) do
      yield block
    end
  end
end

app/views/collections/_childrens.html.erb
<%# locals: (living_unit:, collection:) -%>
<li id="<%= dom_id(living_unit, :sidebar) %>">
  <%= drawer_link(real_estate_living_unit_path(collection, living_unit)) do %>
    <span>
      <%= icon(:document, css: "size-6") %>
    </span>
    <div id="<%= dom_id(living_unit, :name) %>">
      <%= living_unit.name %>
    </div>
  <% end %>
</li>

app/views/collections/_collection.html.erb
<%# locals: (collection:, user_id:) -%>

<li id="<%= dom_id(collection, :sidebar) %>">
  <details
    <%= collapsed?(collection, user_id:) %>
    data-action="click->drawer#collapseToggle"
    data-drawer-id-param="<%= collection.id %>"
  >
    <summary class="group">
      <span>
        <%= icon(:folder, css: "size-6 stroke-accent") %>
      </span>
      <div id="<%= dom_id(collection, :name) %>">
        <%= collection.name %>
      </div>
    </summary>
    <ul id="<%= dom_id(collection, :sidebar_childrens) %>">
      <li class="mt-2">
        <%= drawer_link(real_estate_path(collection)) do %>
          <span>
            <%= icon(:document_text, css: "size-6") %>
          </span>
          <%= t("collection.overview") %>
        <% end %>
      </li>
      <% collection.childrens.each do |living_unit| %>
        <%= render "collections/childrens", living_unit:, collection: %>
      <% end %>
    </ul>
  </details>
</li>

app/views/collections/_form.html.erb
<%= simple_form_for(@collection, wrapper: :inline) do |f| %>
  <%= f.input :name, input_html: { class: "w-full" } %>

  <%= link_to I18n.t("button.back"),
  (@collection.new_record? ? collections_path : collection_path(@collection)),
  class: "btn btn-secondary w-full mt-2",
  data: {
    turbo_frame: "main_content",
  } %>

  <%= f.button :submit, class: "btn btn-primary w-full mt-2" %>
<% end %>

app/views/collections/create.turbo_stream.erb
<%= turbo_stream.replace "main_content" do %>
  <%= render template: "collections/show" %>
<% end %>

app/views/collections/index.html.erb
<%= turbo_frame_tag :sidebar do %>
  <ul class="menu px-4 py-0 w-full" id="sidebar_list" data-turbo-permanent>
    <%= render @collections, user_id: Current.user.id %>
  </ul>
<% end %>

app/views/collections/new.html.erb
<%= turbo_frame_tag :main_content do %>
  <%= turbo_frame_tag :new_real_estate, src: new_real_estate_path %>
<% end %>

app/views/collections/show.html.erb
<%= main_turbo_frame_tag dom_id(@collection) do %>
  <%= render "shared/default_box", title: I18n.t("collection.headline.show") do %>
    <%= @collection.name %>
    <div class="card-actions justify-end">
      <%= link_to I18n.t("button.destroy"),
      collection_path(@collection),
      class: "btn btn-secondary",
      data: {
        turbo_confirm: I18n.t("turbo.confirm.destroy"),
        turbo_method: :delete,
        turbo_frame: "_top",
      } %>

      <%= link_to I18n.t("button.edit"),
      edit_collection_path(@collection),
      class: "btn btn-primary" %>

    </div>
  <% end %>
<% end %>

app/views/collections/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@collection, :sidebar) do %>
  <%= render @collection, user_id: Current.user.id %>
<% end %>