config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Internal
  resource :session, only: [:new, :create, :destroy]

  # App
  scope :charts do
    get :consumer_indicies, to: "charts#consumer_indicies", as: :consumer_index_chart
  end
  resource :calculator, only: [:show, :create]
  resources :consumer_indicies, only: [:show]

  resources :collections, only: [:index, :new, :update]
  resources :real_estates do
    resources :living_units, path: :units, except: [:index, :new]
  end

  resources :living_units, path: :units, only: [] do
    resources :rentals
    resources :rents, except: [:show, :edit, :update]
    resources :tenants, except: [:show, :edit, :update]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "real_estates#index"
end

app/models/concerns/broadcast/living_unit.rb
# frozen_string_literal: true

module Broadcast
  module LivingUnit
    extend ActiveSupport::Concern

    included do
      after_update_commit do
        broadcast_update_later_to(:events, target: "name_living_unit_#{id}", html: name)
        broadcast_replace_later_to(
          :events,
          target: "edit_living_unit_#{id}",
          partial: "living_units/form",
          locals: { disabled: true, real_estate: real_estate, living_unit: self },
        )
      end
      after_create_commit do
        broadcast_append_later_to(
          :events,
          target: "sidebar_childrens_collection_#{real_estate_id}",
          partial: "collections/childrens",
          locals: { collection: real_estate, living_unit: self },
        )
      end
      after_destroy_commit do
        broadcast_remove_to(:events, target: "sidebar_living_unit_#{id}")
      end
    end
  end
end

app/models/living_unit.rb
# frozen_string_literal: true

class LivingUnit < ApplicationRecord
  include Broadcast::LivingUnit
  belongs_to :real_estate

  after_initialize :set_default

  has_many :tenants, dependent: :destroy
  has_many :rents, dependent: :destroy

  store_accessor :properties,
    :rooms,
    :living_space,
    :own_use

  validates :name, presence: true
  validates :living_space, :rooms, numericality: true

  class << self
    def accessable(user: Current.user)
      where(real_estate_id: user.real_estate_ids)
    end
  end

  private

  def set_default
    self.name ||= I18n.t("living_unit.default.name")
    self.rooms ||= 0
    self.living_space ||= 0
  end
end

app/controllers/living_units_controller.rb
# frozen_string_literal: true

class LivingUnitsController < ApplicationController
  before_action :set_real_estate
  before_action :set_living_unit, only: [:show, :edit, :update, :destroy]
  before_action :can_manage?, only: [:create, :update, :destroy]

  def show
  end

  def edit
  end

  def create
    @living_unit = @real_estate.living_units.new

    respond_to do |format|
      if @living_unit.save
        format.turbo_stream
        format.html { redirect_to([@real_estate, @living_unit], notice: "LivingUnit was successfully created.") }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @living_unit.update(living_unit_params)
        format.html { redirect_to([@real_estate, @living_unit], notice: "LivingUnit was successfully updated.") }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @living_unit.destroy!

    respond_to do |format|
      format.html do
        redirect_to(
          real_estate_path(@real_estate),
          status: :see_other,
          notice: "LivingUnit was successfully destroyed.",
        )
      end
    end
  end

  private

  def can_manage?
    head(:forbidden) unless @real_estate.can_manage?
  end

  def set_real_estate
    @real_estate = RealEstate.accessable.find(params[:real_estate_id])
  end

  def set_living_unit
    @living_unit = @real_estate.living_units.find(params[:id])
  end

  def living_unit_params
    params.require(:living_unit).permit(
      :name,
      :description,
      :rooms,
      :living_space,
      :own_use,
    )
  end
end

app/views/living_units/_action_bar.html.erb
<%# locals: (real_estate: nil, living_unit: nil, hide_action_bar: true) -%>

<div class="flex">
  <div class="basis-1/2">
  </div>
  <div class="basis-1/2 flex justify-end">
    <%= link_to edit_real_estate_living_unit_path(real_estate, living_unit),
        class: "btn btn-circle btn-outline mr-2 tooltip inline-flex #{class_names(hidden: hide_action_bar)}",
    data: {
      tip: t("living_unit.tooltip.edit")
    } do %>
      <%= icon(:pencil, css: "size-6") %>
    <% end %>
    <%= link_to real_estate_living_unit_path(real_estate, living_unit),
    class: "btn btn-circle btn-outline tooltip inline-flex",
    data: {
      tip: t("living_unit.tooltip.destroy"),
      turbo_method: :delete,
      turbo_confirm: t("turbo.confirm.destroy"),
      turbo_frame: "_top",
    } do %>
      <%= icon(:trash, css: "size-6") %>
    <% end %>
  </div>
</div>

app/views/living_units/_form.html.erb
<%# locals: (real_estate: nil, living_unit: nil, disabled: false, cancel_url: real_estate_living_unit_path(real_estate, living_unit), turbo_frame: dom_id(living_unit)) -%>

<%= simple_form_for([real_estate, living_unit])  do |f| %>
  <div class="flex flex-col gap-2">
    <div class="flex">
      <div class="basis-full rounded p-4 bg-base-300">
        <%= f.input :name, required: false, disabled: %>
        <%= f.input :description, as: :text, input_html: { cols: 40 }, disabled: %>
      </div>
    </div>
    <div class="flex">
      <div class="basis-1/2 rounded p-4 bg-base-300">
        <%= f.input :rooms, as: :float, disabled: %>
        <%= f.input :living_space, as: :float, disabled: %>
      </div>
      <div class="basis-1/2 rounded p-4 bg-base-300">
        <%= f.input :own_use, as: :boolean, disabled: %>
      </div>
    </div>
    <% unless disabled %>
      <%= link_to t("button.cancel"),
      cancel_url,
      class: "btn btn-secondary mt-2",
      data: {
        turbo_frame: turbo_frame,
      } %>

      <%= f.button :submit, class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
<% end %>

app/views/living_units/_tablist.html.erb
<%# locals: (living_unit: nil, real_estate: nil, disabled: true, hide_action_bar: true) -%>
<div class="flex flex-col gap-2">
  <div class="flex">
    <div role="tablist" class="basis-full tabs tabs-lifted tabs-lg">
      <%= render "shared/tab", url: real_estate_living_unit_path(real_estate, living_unit), active: true, label: t("living_unit.tab.tab_1") do %>
        <div class="flex flex-col gap-2">
          <div class="flex">
            <div class="basis-full">
              <%= render "living_units/action_bar", real_estate:, living_unit:, hide_action_bar: %>
            </div>
          </div>
          <div class="flex">
            <div class="basis-full">
              <%= render "form", real_estate:, living_unit:, disabled: %>
            </div>
          </div>
        </div>
      <% end %>

      <%= tab_link t("living_unit.tab.tab_2"),
      url: living_unit_rentals_path(living_unit),
      disabled: !disabled %>
    </div>
  </div>
</div>

app/views/living_units/edit.html.erb
<%= main_turbo_frame_tag dom_id(@living_unit) do %>
  <%= render "tablist",
  real_estate: @real_estate,
  living_unit: @living_unit,
  disabled: false %>
<% end %>

app/views/living_units/show.html.erb
<%= main_turbo_frame_tag dom_id(@living_unit) do %>
  <%= render "tablist",
  real_estate: @real_estate,
  living_unit: @living_unit,
  hide_action_bar: false %>
<% end %>