config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Internal
  resource :session, only: [:new, :create, :destroy]

  # App
  scope :charts do
    get :consumer_indicies, to: "charts#consumer_indicies", as: :consumer_index_chart
  end
  resource :calculator, only: [:show, :create]
  resources :consumer_indicies, only: [:show]

  resources :collections, only: [:index, :new, :update]
  resources :real_estates do
    resources :living_units, path: :units, except: [:index, :new]
  end

  resources :living_units, path: :units, only: [] do
    resources :rentals
    resources :rents, except: [:show, :edit, :update]
    resources :tenants, except: [:show, :edit, :update]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "real_estates#index"
end

app/models/concerns/broadcast/rental.rb
# frozen_string_literal: true

module Broadcast
  module Rental
    extend ActiveSupport::Concern

    included do
      after_update_commit do
        if archived?
          broadcast_remove_to(
            :events,
            target: "index_rental_#{id}",
          )
          broadcast_prepend_later_to(
            :events,
            target: "archived_rentals_living_unit_#{living_unit_id}",
            partial: "rentals/rental",
            locals: { rental: self, living_unit: living_unit },
          )
        else
          broadcast_update_later_to(
            :events,
            target: "edit_rental_#{id}",
            partial: "rentals/form",
            locals: { rental: self, living_unit: living_unit, disabled: true },
          )
          broadcast_update_later_to(
            :events,
            target: "index_rental_#{id}",
            partial: "rentals/rental",
            locals: { rental: self, living_unit: living_unit },
          )
        end
      end

      after_create_commit do
        broadcast_prepend_later_to(
          :events,
          target: "active_rentals_living_unit_#{living_unit_id}",
          partial: "rentals/rental",
          locals: { rental: self, living_unit: living_unit },
        )
      end
    end
  end
end

app/models/rental.rb
# frozen_string_literal: true

class Rental < ApplicationRecord
  include Broadcast::Rental
  belongs_to :living_unit
  has_many :tenants, dependent: :destroy
  has_many :rents, dependent: :destroy

  scope :active, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }

  accepts_nested_attributes_for :tenants, :rents, reject_if: :all_blank

  delegate :real_estate, to: :living_unit

  after_initialize :build_associations, if: :new_record?

  store :properties,
    accessors: [
      :description,
    ],
    coder: JSON

  validates :valid_from, :description, presence: true

  def archive!
    update(archived: true)
  end

  private

  def build_associations
    tenants.build if tenants.empty?
    rents.build if rents.empty?
  end
end

app/controllers/rentals_controller.rb
# frozen_string_literal: true

class RentalsController < ApplicationController
  before_action :set_real_estate_living_unit
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :can_manage?, only: [:create, :update, :destroy]

  def index
    @active_rentals = @living_unit.rentals.active
    @archived_rentals = @living_unit.rentals.archived
  end

  def new
    @rental = Rental.new
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @rental.update(update_rental_params)
        format.html do
          redirect_to(
            living_unit_rental_path(@living_unit, @rental),
            notice: "Rental was successfully updated.",
          )
        end
      else
        format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def create
    @rental = @living_unit.rentals.new(rental_params)
    respond_to do |format|
      if @rental.save
        format.html do
          redirect_to(
            living_unit_rentals_path(@living_unit),
            notice: "Rental was successfully created.",
          )
        end
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @rental.archive!
    @active_exists = @living_unit.rentals.active.exists?

    respond_to do |format|
      format.turbo_stream do
        flash.now[:notice] = "Rental was successfully archived."
      end
      format.html do
        redirect_to(
          living_unit_rentals_path(@living_unit),
          status: :see_other,
          notice: "Rental was successfully archived.",
        )
      end
    end
  end

  private

  def can_manage?
    head(:forbidden) unless @real_estate.can_manage?
  end

  def set_real_estate_living_unit
    @living_unit = LivingUnit.accessable.find(params[:living_unit_id]).tap do |living_unit|
      @real_estate = living_unit.real_estate
    end
  end

  def set_rental
    @rental = @living_unit.rentals.find(params[:id])
  end

  def update_rental_params
    params.require(:rental).permit(
      :description,
      :valid_from,
    )
  end

  def rental_params
    params.require(:rental).permit(
      :description,
      :valid_from,
      tenants_attributes: [
        :first_name,
        :last_name,
        :email,
        :phone_number,
      ],
      rents_attributes: [
        :cold_rent,
        :heating_costs,
        :incidental_costs,
        :rent_type,
        :valid_from,
      ],
    )
  end
end

app/helpers/rentals_helper.rb
# frozen_string_literal: true

module RentalsHelper
  def rent_type_options
    Rent::RENT_TYPES.map do |type|
      [t("simple_form.labels.rent.rent_types.#{type}"), type]
    end
  end
end

app/views/rentals/_action_bar.html.erb
<%# locals: (living_unit: nil, rental:, index: false, hide_action_bar: true) -%>
<div class="flex">
  <div class="basis-1/2">
    <% if index %>
      <%= link_to t("rental.button.new"),
      new_living_unit_rental_path(living_unit),
      class: "btn btn-primary" %>
    <% elsif !hide_action_bar %>
      <%= link_to t("button.cancel"),
      living_unit_rentals_path(living_unit),
      class: "btn btn-primary",
      data: {
        turbo_frame: "main_content",
      } %>
    <% end %>
  </div>
  <div class="basis-1/2 flex justify-end">
    <% unless hide_action_bar %>
      <%= link_to edit_living_unit_rental_path(living_unit, rental),
        class: "btn btn-circle btn-outline mr-2 tooltip inline-flex",
        data: {
          tip: t("rental.tooltip.edit")
        } do %>
        <%= icon(:pencil, css: "size-6") %>
      <% end %>

      <%= button_to living_unit_rental_path(living_unit, rental),
        class: "btn btn-circle btn-outline tooltip inline-flex",
        method: :delete,
        data: {
          tip: t("rental.tooltip.archive"),
          turbo_confirm: t("turbo.confirm.destroy"),
          turbo: false,
        } do %>
        <%= icon(:archive, css: "size-6") %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rentals/_form.html.erb
<%# locals: (living_unit: nil, rental: nil, cancel_url: nil, turbo_frame: dom_id(rental), disabled: false) -%>

<%= simple_form_for([living_unit, rental]) do |f| %>
  <div class="flex flex-col gap-2" data-controller="rental">
    <%= render "rentals/form/master_data", f:, disabled:, living_unit:, rental: %>

    <% if rental.new_record? %>
      <%= render "rentals/form/tenants", f:, remove_tenant: @rental.tenants.size == 1 %>
      <%= render "rentals/form/rent", f: %>
    <% end %>

    <% unless disabled %>
      <%= link_to t("button.cancel"),
      cancel_url,
      class: "btn btn-secondary mt-2",
      data: {
        turbo_frame: turbo_frame,
      } %>

      <%= f.button :submit, class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
<% end %>

app/views/rentals/_rental.html.erb
<div
  class="basis-full bg-base-300 rounded-lg min-h-24 p-2 flex flex-row"
  id="<%= dom_id(rental, :index) %>"
>
  <div class="flex flex-1">
    <div class="basis-1/2">
      <p class="font-semibold">
        <%= t("rental.label.description") %>
      </p>
      <div class="mt-2">
        <%= rental.description %>
      </div>
    </div>
    <div class="basis-1/2 flex justify-end items-center">
      <% unless rental.archived? %>
        <%= link_to living_unit_rental_path(living_unit, rental),
          class: "btn btn-circle btn-outline mr-2 tooltip inline-flex",
          data: {
            turbo_method: :delete,
            tip: t("rental.tooltip.archive")
          } do %>
          <%= icon(:archive, css: "size-6") %>
        <% end %>
      <% end %>
      <%= link_to t("rental.button.show"),
      living_unit_rental_path(living_unit, rental),
      class: "btn btn-info mr-2",
      data: {
        turbo_frame: "main_content",
      } %>
    </div>
  </div>
</div>

app/views/rentals/_rentals.html.erb
<%# locals: (collection: [], label: nil, mt: false) -%>
<%= content_tag(
      "div",
      class: class_names("flex flex-col gap-2", { "mt-6": mt }),
    ) do %>

  <div class="flex mt-2">
    <div class="basis-1/2">
      <p class="font-semibold pl-2">
        <%= t("rental.#{label}") %>
      </p>
    </div>
    <div class="basis-1/2 flex justify-end">
    </div>
  </div>
  <div
    class="flex flex-col gap-2"
    id="<%= dom_id(@living_unit, "#{label}_rentals") %>"
  >
    <%= render(collection, living_unit: @living_unit) %>
  </div>
<% end %>

app/views/rentals/_tablist.html.erb
<%# locals: (real_estate: nil, living_unit: nil, rental:, cancel_url: living_unit_rentals_path(living_unit), disabled: true, hide_action_bar: true, index: false) -%>
<div class="flex flex-col gap-2">
  <div class="flex">
    <div role="tablist" class="basis-full tabs tabs-lifted tabs-lg">
      <%= tab_link t("rental.tab.tab_1"),
      url: real_estate_living_unit_path(real_estate, living_unit),
      disabled: !disabled %>

      <%= render "shared/tab", url: living_unit_rentals_path(living_unit), active: true, label: t("rental.tab.tab_2") do %>
        <div class="flex flex-col gap-2">

          <%= render "rentals/action_bar", living_unit:, rental:, index:, hide_action_bar: %>

          <div class="flex">
            <div class="basis-full">
              <% unless index %>
                <%= render "form", living_unit:, rental:, disabled:, cancel_url: %>
              <% end %>

              <%= yield if block_given? %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@rental, :index) %>
<%= turbo_stream.prepend dom_id(@living_unit, "archived_rentals"),
                     partial: "rentals/rental",
                     locals: {
                       rental: @rental,
                       living_unit: @living_unit,
                     } %>
<%= render_turbo_stream_flash_messages %>

app/views/rentals/edit.html.erb
<%= main_turbo_frame_tag dom_id(@rental) do %>
  <%= render "tablist",
  real_estate: @real_estate,
  living_unit: @living_unit,
  rental: @rental,
  disabled: false,
  cancel_url: living_unit_rental_path(@living_unit, @rental),
  hide_action_bar: true %>
<% end %>

app/views/rentals/index.html.erb
<%= main_turbo_frame_tag dom_id(@living_unit, :rentals) do %>
  <%= render "tablist",
  real_estate: @real_estate,
  living_unit: @living_unit,
  rental: nil,
  index: true do %>

    <%= render "rentals", collection: @active_rentals, label: "active" %>
    <%= render "rentals", collection: @archived_rentals, label: "archived", mt: true %>
  <% end %>
<% end %>

app/views/rentals/new.html.erb
<%= main_turbo_frame_tag dom_id(@living_unit, :rentals) do %>
  <%= render "tablist",
  real_estate: @real_estate,
  living_unit: @living_unit,
  rental: @rental,
  hide_action_bar: true,
  cancel_url: living_unit_rentals_path(@living_unit),
  disabled: false do %>
  <% end %>
<% end %>

app/views/rentals/show.html.erb
<%= main_turbo_frame_tag dom_id(@rental) do %>
  <%= render "tablist",
  real_estate: @real_estate,
  living_unit: @living_unit,
  rental: @rental,
  hide_action_bar: false %>
<% end %>