config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Internal
  resource :session, only: [:new, :create, :destroy]

  # App
  scope :charts do
    get :consumer_indicies, to: "charts#consumer_indicies", as: :consumer_index_chart
  end
  resource :calculator, only: [:show, :create]
  resources :consumer_indicies, only: [:show]

  resources :collections, only: [:index, :new, :update]
  resources :real_estates do
    resources :living_units, path: :units, except: [:index, :new]
  end

  resources :living_units, path: :units, only: [] do
    resources :rentals
    resources :rents, except: [:show, :edit, :update]
    resources :tenants, except: [:show, :edit, :update]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "real_estates#index"
end

app/models/concerns/broadcast/real_estate.rb
# frozen_string_literal: true

module Broadcast
  module RealEstate
    extend ActiveSupport::Concern

    included do
      after_update_commit do
        broadcast_update_later_to(
          :events,
          target: "edit_real_estate_#{id}",
          partial: "real_estates/form",
          locals: { disabled: true, real_estate: self },
        )
      end
    end
  end
end

app/models/real_estate.rb
# frozen_string_literal: true

class RealEstate < ApplicationRecord
  include Memberable, Collectable, Broadcast::RealEstate

  HEATING_TYPES = ["heat_pump_air", "heat_pump_water", "oil", "gas"].freeze
  DATE_FORMAT = %r{\A(0?[1-9]|1[0-2])\/\d{4}\z}

  store_accessor :address, :street, :zip_code, :city
  store_accessor :heating,
    :type,
    :manufacturer,
    :designation,
    :installed_at,
    prefix: true

  store_accessor :properties,
    :units,
    :space,
    :built_at,
    :renovated_at,
    :energy_certificate

  store_accessor :solar_plant,
    :present,
    :manufacturer,
    :capacity,
    :designation,
    :battery_capacity,
    :installed_at,
    prefix: true

  has_many :living_units, dependent: :destroy

  validates :name, :street, :city, presence: true
  validates :zip_code, :space, :units, numericality: true
  validates :heating_type, inclusion: { in: HEATING_TYPES }
  validates :renovated_at,
    :built_at,
    :heating_installed_at,
    format: { with: DATE_FORMAT, message: :date_format },
    allow_blank: true

  with_options if: :solar_plant_present? do
    validates :solar_plant_capacity, numericality: true
    validates :solar_plant_battery_capacity, numericality: true, allow_nil: true
    validates :solar_plant_installed_at, format: { with: DATE_FORMAT, message: :date_format }
  end

  def childrens
    living_units
  end

  def solar_plant_present
    super || false
  end

  def solar_plant_present?
    solar_plant_present == "1"
  end
end

app/controllers/real_estates_controller.rb
# frozen_string_literal: true

class RealEstatesController < ApplicationController
  before_action :set_real_estate, only: [:show, :edit, :update, :destroy]
  before_action :can_manage?, only: [:edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @real_estate = RealEstate.new
  end

  def edit
  end

  def create
    @real_estate = RealEstate.new(real_estate_params)

    respond_to do |format|
      if @real_estate.save
        format.turbo_stream
        format.html { redirect_to(@real_estate, notice: "RealEstate was successfully created.") }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @real_estate.update(real_estate_params)
        format.html { redirect_to(@real_estate, notice: "RealEstate was successfully updated.") }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @real_estate.destroy!

    respond_to do |format|
      format.html do
        redirect_to(real_estates_path, status: :see_other, notice: "RealEstate was successfully destroyed.")
      end
    end
  end

  private

  def can_manage?
    head(:forbidden) unless @real_estate.can_manage?
  end

  def set_real_estate
    @real_estate = RealEstate.accessable.find(params[:id])
  end

  def real_estate_params
    params.require(:real_estate).permit(
      :name,
      :street,
      :zip_code,
      :city,
      :units,
      :space,
      :built_at,
      :renovated_at,
      :energy_certificate,
      :heating_type,
      :heating_manufacturer,
      :heating_designation,
      :heating_installed_at,
      :solar_plant_present,
      :solar_plant_manufacturer,
      :solar_plant_capacity,
      :solar_plant_designation,
      :solar_plant_battery_capacity,
      :solar_plant_installed_at,
      :size,
    )
  end
end

app/views/real_estates/_action_bar.html.erb
<%# locals: (real_estate: nil, disabled: false) -%>
<div class="flex">
  <div class="basis-1/2">
    <%= button_to t("living_unit.button.create"),
    real_estate_living_units_path(real_estate),
    class: "btn btn-primary mr-2 tooltip inline-flex",
    data: {
      tip: t("living_unit.tooltip.create"),
      turbo: false,
      turbo_frame: "_top",
    } %>
  </div>
  <div class="basis-1/2 flex justify-end">
    <% if disabled %>
      <%= link_to edit_real_estate_path(real_estate),
    class: "btn btn-circle btn-outline mr-2 tooltip inline-flex",
    data: { tip: t("real_estate.tooltip.edit") } do %>
        <%= icon(:pencil, css: "size-6") %>
      <% end %>
    <% end %>
    <%= link_to real_estate_path(real_estate),
    class: "btn btn-circle btn-outline tooltip inline-flex",
    data: {
      tip: t("real_estate.tooltip.destroy"),
      turbo_method: :delete,
      turbo_confirm: t("turbo.confirm.destroy"),
      turbo_frame: "_top",
    } do %>
      <%= icon(:trash, css: "size-6") %>
    <% end %>
  </div>
</div>

app/views/real_estates/_form.html.erb
<%# locals: (real_estate: nil, disabled: false, cancel_url: real_estate_path(real_estate), turbo_frame: dom_id(real_estate)) -%>
<%= simple_form_for(real_estate, data: { controller: "real-estate" })  do |f| %>
  <div class="flex flex-col gap-2">
    <div class="flex">
      <div class="basis-full rounded p-4 bg-base-300">
        <%= f.input :name, required: false, disabled: %>
      </div>
    </div>

    <div class="flex gap-2">
      <div class="basis-1/2 rounded p-4 bg-base-300">
        <h3 class="font-bold mb-4">
          <%= t("real_estate.form.section.address") %>
        </h3>
        <%= f.input :street, required: false, disabled: %>
        <%= f.input :zip_code, as: :integer, disabled: %>
        <%= f.input :city, required: false, disabled: %>
      </div>

      <div class="basis-1/2 rounded p-4 bg-base-300">
        <h3 class="font-bold mb-4">
          <%= t("real_estate.form.section.properties") %>
        </h3>
        <%= f.input :renovated_at, as: :string, disabled: %>
        <%= f.input :built_at, as: :string, disabled: %>
        <%= f.input :energy_certificate, as: :boolean, disabled: %>
        <%= f.input :units, as: :integer, disabled: %>
        <%= f.input :space, as: :integer, disabled: %>
      </div>
    </div>

    <div class="flex gap-2">
      <div class="basis-1/2 rounded p-4 bg-base-300">
        <h3 class="font-bold mb-4">
          <%= t("real_estate.form.section.heating") %>
        </h3>
        <%= f.input :heating_type,
                collection:
                  RealEstate::HEATING_TYPES.map { |type|
                    [t("simple_form.labels.real_estate.heating_types.#{type}"), type]
                  },
                disabled: %>
        <%= f.input :heating_manufacturer, as: :string, disabled: %>
        <%= f.input :heating_designation, as: :string, disabled: %>
        <%= f.input :heating_installed_at, as: :string, disabled: %>
      </div>
      <% if real_estate.solar_plant_present? || !disabled %>
        <div class="basis-1/2 rounded p-4 bg-base-300">
          <h3 class="font-bold mb-4">
            <%= t("real_estate.form.section.solar_plant") %>
          </h3>
          <%= unless disabled
            f.input :solar_plant_present,
                    as: :boolean,
                    disabled:,
                    input_html: {
                      data: {
                        action: "click->real-estate#toggleEnableDisable",
                      },
                    }
          end %>
          <%= f.input :solar_plant_manufacturer,
                  as: :string,
                  disabled:,
                  input_html: {
                    data: {
                      "real-estate-target": "field",
                    },
                  } %>
          <%= f.input :solar_plant_designation,
                  as: :string,
                  disabled:,
                  input_html: {
                    data: {
                      "real-estate-target": "field",
                    },
                  } %>
          <%= f.input :solar_plant_capacity,
                  as: :string,
                  disabled:,
                  input_html: {
                    data: {
                      "real-estate-target": "field",
                    },
                  } %>
          <%= f.input :solar_plant_battery_capacity,
                  as: :string,
                  disabled:,
                  input_html: {
                    data: {
                      "real-estate-target": "field",
                    },
                  } %>
          <%= f.input :solar_plant_installed_at,
                  as: :string,
                  disabled:,
                  input_html: {
                    data: {
                      "real-estate-target": "field",
                    },
                  } %>
        </div>
      <% end %>
    </div>

    <% unless disabled %>
      <%= link_to t("button.cancel"),
      cancel_url,
      class: "btn btn-secondary mt-2",
      data: {
        turbo_frame: turbo_frame,
      } %>

      <%= f.button :submit, class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
<% end %>

app/views/real_estates/_tablist.html.erb
<%# locals: (real_estate: nil, disabled: true) -%>
<div class="flex flex-col gap-2">
  <div class="flex">
    <div role="tablist" class="basis-full tabs tabs-lifted tabs-lg">
      <%= render "shared/tab", url: real_estate_path(real_estate), active: true, label: t("real_estate.tab.tab_1") do %>
        <div class="flex flex-col gap-2">
          <div class="flex">
            <div class="basis-full">
              <%= render "real_estates/action_bar", real_estate:, disabled: %>
            </div>
          </div>
          <div class="flex">
            <div class="basis-full">
              <%= render "form", disabled:, real_estate: %>
            </div>
          </div>
        </div>
      <% end %>

      <%= tab_link t("real_estate.tab.tab_2"), disabled: !disabled %>
      <%= tab_link t("real_estate.tab.tab_3"), disabled: !disabled %>
    </div>
  </div>
</div>

app/views/real_estates/create.turbo_stream.erb
<%= turbo_stream.replace "main_content" do %>
  <%= render template: "real_estates/show" %>
<% end %>

app/views/real_estates/edit.html.erb
<%= main_turbo_frame_tag dom_id(@real_estate) do %>
  <%= render "tablist", real_estate: @real_estate, disabled: false %>
<% end %>

app/views/real_estates/index.html.erb
<%= turbo_frame_tag "main_content" do %>
  <div class="grid lg:grid-rows-4 lg:grid-cols-3 gap-4">
    <div class="lg:col-span-1 lg:row-span-4">
      Welcome!
    </div>
    <div class="lg:col-span-2 lg:row-span-4 flex lg:justify-center pr-4">
      <%= turbo_frame_tag :calculator, src: calculator_path %>
    </div>
  </div>
<% end %>

app/views/real_estates/new.html.erb
<%= main_turbo_frame_tag dom_id(@real_estate) do %>
  <%= render "form",
  cancel_url: root_path,
  turbo_frame: "main_content",
  real_estate: @real_estate %>
<% end %>

app/views/real_estates/show.html.erb
<%= main_turbo_frame_tag dom_id(@real_estate) do %>
  <%= render "tablist", real_estate: @real_estate %>
<% end %>